default_language_version:
  python: python3.7

default_stages: [commit, push]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: LICENSE

  # remove unused import and variable using autoflake
  - repo: https://github.com/PyCQA/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        args: [
          '--in-place',
          '--remove-all-unused-imports',
          '--ignore-init-module-imports',
          '--remove-unused-variables',
          '--'
        ]

  # use latest syntax
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.32.1
    hooks:
    -   id: pyupgrade

  # follow style using autopep8
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.6.0
    hooks:
      - id: autopep8

  # sort import using isort
  - repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
      - id: isort

  # linting and code analysis using flake8
  # flake8 here is mostly redundant, but used for some style that skipped by
  # autoflake8 and autopep8
  - repo: https://github.com/pycqa/flake8
    rev: 3.8.3
    hooks:
      - id: flake8
        args: [
          '--max-line-length',
          '88',
          '--'
        ]
