repos:
  # check yaml and end of file fixer
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: LICENSE

  # autofix using autopep8
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.1
    hooks:
      - id: autopep8

  # checkstyle using ruff
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.0.226'
    hooks:
      - id: ruff
