[tool.pytest.ini_options]
# https://docs.pytest.org/en/6.2.x/customize.html#pyproject-toml
# Directories that are not visited by pytest collector:
norecursedirs =["hooks", "*.egg", ".eggs", "dist", "build", "docs", ".tox", ".git", "__pycache__"]

# Extra options:
addopts = [
  "--strict-markers",
  "--tb=short",
]

[tool.coverage.run]
source = ["tests"]

[coverage.paths]
source = "sortfolder"

[coverage.run]
branch = true

[coverage.report]
fail_under = 50
show_missing = true
